# Generated by Django 3.1.2 on 2021-01-04 21:37

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('idEquipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Equipo')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('url_escudo', models.URLField(verbose_name='URL del escudo')),
            ],
            options={
                'db_table': 'Equipos',
                'ordering': ('nombre', 'valor', 'idEquipo'),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='PosicionPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Posición principal')),
            ],
        ),
        migrations.CreateModel(
            name='PosicionSecundaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Posición secundaria')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('idJugador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(verbose_name='Jugador')),
                ('edad', models.IntegerField(help_text='Debe introducir una edad', verbose_name='Edad')),
                ('altura', models.FloatField(verbose_name='Altura')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('contrato', models.DateField(verbose_name='Contrato')),
                ('capitan', models.BooleanField()),
                ('foto_jugador', models.URLField(verbose_name='URL de la foto del jugador')),
                ('pie', models.CharField(choices=[(main.models.PieChoice['IZQ'], 'izquierdo'), (main.models.PieChoice['DER'], 'derecho'), (main.models.PieChoice['AMB'], 'ambidiestro'), (main.models.PieChoice['IND'], 'indeterminado')], max_length=3, verbose_name='Pie')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.equipo')),
                ('nacionalidades', models.ManyToManyField(to='main.Pais')),
                ('posicion_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.posicionprincipal')),
                ('posiciones_secundarias', models.ManyToManyField(to='main.PosicionSecundaria')),
            ],
            options={
                'db_table': 'Jugadores',
                'ordering': ('nombre', 'valor', 'idJugador'),
            },
        ),
    ]
